### ISSUE TITLE
Few files are not exposed

### ISSUE THREAD

**Issue by levchak0910** [Smile-SA/slidev-component-poll#2]
Hi @tonai. First of all, thanks for an awesome addon for slidev )

It works perfectly when using as a linked local package, but missing some files when loaded from npm. And because of that, slidev dev/prod mode is broken.

Please fix file paths that should be included into (exposed by) the package: https://github.com/Smile-SA/slidev-component-poll/blob/main/package.json#L14-L18

Current folder structure is looking like this:

- assets
- components
- composables
- constants
- services
- types

So `constants` and `types` are missing

**Comment by tonai** [comment]
Hello @levchak0910, thanks for your feedback.
I just published v2.0.2 with the fix: https://www.npmjs.com/package/slidev-component-poll?activeTab=code

**Comment by levchak0910** [comment]
thanks for quick fix )

**Comment by levchak0910** [comment]
@tonai, one more file is missing `/custom-nav-controls.vue`. Could you please add it too?

**Comment by levchak0910** [comment]
And `/index.d.ts` I suppose too. (I don't use that api, so I am not sure)

Overall, would it be better to expose all files? I searched all available addons, nobody list files in the `package.json`

**Comment by tonai** [comment]
`index.d.ts` is only for types purpose on dev, I don't think it is useful when you install the package, but `custom-nav-controls.vue` is more likely to be needed yes.
I use the `files` entry to shrink the package size to the max.
But yes it is mostly usefull when you build your lib which is not the case with slidev addons so it is probably not necessary here.
I published version v2.0.3 without the `files` entry.

**Comment by levchak0910** [comment]
Great, everything works as expected now. Thank you for quick fixes )

**Comment by levchak0910** [comment]
off-topic:
By the way, is there any conference publicly available where you used this addon?
Could you share the link?
Would it work well for audience of 30-100 people?

**Comment by tonai** [comment]
No there is no public showcase for the addon now and I didn't test it for such an audience.
Maybe you can ask the question on slidev discord because this addon only use slidev apis.
The mouse synchronisation between presenter and slides use the same apis, so maybe someone can tell you about that.

**Comment by levchak0910** [comment]
Clear, thanks )
I will share my experience after the talk

**Comment by tonai** [comment]
This will be greatly appreciated :+1:
